%%
% File: Traffic_Sign_CNN.m
%   Load the tranining and test data sets. Use the convolutional neural
%   network classifier to train and test the model. 
%
% Info:
%   Class: EN.525.670.81 - Machine Learning for Signal Processing
%   Term: Spring 2020
%   Author: Cassie Xia
%

%%
% clear workspace
clear all; close all; clc;

%% 1. Load the training data.
sBasePath = fullfile(fileparts(fullfile(mfilename('fullpath'))),'..','gtsrb-german-traffic-sign/');

sTrainingPath = [sBasePath, 'Train.csv'];

% Find signstrain.mat and signstest.mat
% If not found generate them
curDir = pwd;
filename = [curDir,'/','signstrain.mat'];

if isfile(filename)
    signstrain = load(filename);
else
    % generate matfile
    signstrain = generate_csv2mat(sTrainingPath,filename);
end

%% 2. Load the test data

sTestPath = [sBasePath, 'Test.csv'];

filename = [curDir,'/','signstest.mat'];

if isfile(filename)
    signstest = load(filename);
else
    % generate matfile
    signstest = generate_csv2mat(sTestPath,filename,'imPreProcess',true);
end

% Set train and test data
tr_images = signstrain.A;
tr_labels = signstrain.classes;

test_images = signstest.A;
%test_images = signstest.B;
test_labels = signstest.classes;

% Perform dimensionality reduction
numBasis = 120;
[V, D] = pca_basis(tr_images,numBasis);

% Projections
train_projection = tr_images*V;
test_projection = test_images*V;

% Set train labels for CNN
train_cnn_labels = zeros(length(tr_labels),max(tr_labels)+1);
for i=1:length(tr_labels)
   train_cnn_labels(i,tr_labels(i)+1) = 1; 
end

% Set test labels for CNN
test_cnn_labels = zeros(length(test_labels),max(test_labels)+1);
for i=1:length(test_labels)
   test_cnn_labels(i,test_labels(i)+1) = 1; 
end

%% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created 30-Apr-2020 00:47:16
%
% This script assumes these variables are defined:
%
%   train_projection - input data.
%   train_cnn_labels - target data.

x = train_projection';
t = train_cnn_labels';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainscg';  % Scaled conjugate gradient backpropagation.

% Create a Pattern Recognition Network
hiddenLayerSize = 70;   % can customize for better results
net = patternnet(hiddenLayerSize, trainFcn);

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y);
tind = vec2ind(t);
yind = vec2ind(y);
percentErrors = sum(tind ~= yind)/numel(tind);
correctRate = 1-percentErrors;

% View the Network
view(net)

fprintf('CNN Testing Data from Training - PCA Basis: %d Performance: %d CorrectRate: %f ErrorRate: %f \n',...
    numBasis,...
    performance,...
    correctRate, percentErrors);

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotconfusion(t,y)
%figure, plotroc(t,y)

% % Deployment
% % Change the (false) values to (true) to enable the following code blocks.
% % See the help for each generation function for more information.
% if (false)
%     % Generate MATLAB function for neural network for application
%     % deployment in MATLAB scripts or with MATLAB Compiler and Builder
%     % tools, or simply to examine the calculations your trained neural
%     % network performs.
%     genFunction(net,'myNeuralNetworkFunction');
%     y = myNeuralNetworkFunction(x);
% end
% if (false)
%     % Generate a matrix-only MATLAB function for neural network code
%     % generation with MATLAB Coder tools.
%     genFunction(net,'myNeuralNetworkFunction','MatrixOnly','yes');
%     y = myNeuralNetworkFunction(x);
% end
% if (false)
%     % Generate a Simulink diagram for simulation or deployment with.
%     % Simulink Coder tools.
%     gensim(net);
% end

%% Test against testing data
x1 = test_projection';
t1 = test_cnn_labels';
% Test the Network
y1 = net(x1);
e1 = gsubtract(t1,y1);
performance1 = perform(net,t1,y1);
tind1 = vec2ind(t1);
yind1 = vec2ind(y1);
percentErrors1 = sum(tind1 ~= yind1)/numel(tind1);
correctRate1 = 1-percentErrors1;

fprintf('CNN Testing Data from Test - PCA Basis: %d Performance: %d CorrectRate: %f ErrorRate: %f \n',...
    numBasis,...
    performance1,...
    correctRate1, percentErrors1);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Part 2 with Hue Histogram
%  Performance is quite a bit better with the PCA basis
%% Setup

%basePath = 'C:/Users/casxi/Google Drive/Documents/JHU/Machine Learning for Signal Processing/Final Project/gtsrb-german-traffic-sign/'; 
basePath = fullfile(fileparts(fullfile(mfilename('fullpath'))),'..','gtsrb-german-traffic-sign/');

trainCsv = 'Train.csv';
testCsv = 'Test.csv';
metaCsv = 'Meta.csv';

%% Data Conditioning

% [OPTIONAL]Only use the highest quality training and test images
[trainPaths, trainWidths, trainHeights, trainRoiX1, trainRoiY1, trainRoiX2, trainRoiY2, trainClasses]  = reduce_dataset(basePath, trainCsv, .75, .75);
[testPaths, testWidths, testHeights, testRoiX1, testRoiY1, testRoiX2, testRoiY2, testClasses]  = reduce_dataset(basePath, testCsv, .75, .75);

% [OPTIONAL] Do further histogram equalization?

% [OPTIONAL] Generate new data to reduce class skew

%% Feature Extraction

% Extract Hue Histogram features
train_hue_features = get_hue_histograms(basePath, trainPaths, trainRoiX1, trainRoiY1, trainRoiX2, trainRoiY2, 100);
test_hue_features = get_hue_histograms(basePath, testPaths, testRoiX1, testRoiY1, testRoiX2, testRoiY2, 100);

% trainClasses, testClasses
% Set train labels for Hue Histogram features
train_hh_labels = zeros(length(trainClasses),max(trainClasses)+1);
for i=1:length(trainClasses)
   train_hh_labels(i,trainClasses(i)+1) = 1; 
end

% Set test labels for Hue Histogram features
test_hh_labels = zeros(length(testClasses),max(testClasses)+1);
for i=1:length(testClasses)
   test_hh_labels(i,testClasses(i)+1) = 1; 
end

%% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created 01-May-2020 02:02:18
%
% This script assumes these variables are defined:
%
%   train_hue_features - input data.
%   train_hh_labels - target data.

xx = train_hue_features';
tt = train_hh_labels';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainscg';  % Scaled conjugate gradient backpropagation.

% Create a Pattern Recognition Network
hiddenLayerSize = 10;   % can customize for better results, more or less similar
neth = patternnet(hiddenLayerSize, trainFcn);

% Setup Division of Data for Training, Validation, Testing
neth.divideParam.trainRatio = 70/100;
neth.divideParam.valRatio = 15/100;
neth.divideParam.testRatio = 15/100;

% Train the Network
[neth,tr] = train(neth,xx,tt);

% Test the Network
yy = neth(xx);
ee = gsubtract(tt,yy);
performance = perform(neth,tt,yy);
tind = vec2ind(tt);
yind = vec2ind(yy);
percentErrors = sum(tind ~= yind)/numel(tind);
correctRate = 1-percentErrors;

% View the Network
view(neth)

fprintf('CNN Testing Data from Training - Hue Histogram Features Performance: %d CorrectRate: %f ErrorRate: %f \n',...
    performance,...
    correctRate, percentErrors);

%% Test against testing data
xx1 = test_hue_features';
tt1 = test_hh_labels';
% Test the Network
yy1 = neth(xx1);
ee1 = gsubtract(tt1,yy1);
performance1 = perform(neth,tt1,yy1);
tind1 = vec2ind(tt1);
yind1 = vec2ind(yy1);
percentErrors1 = sum(tind1 ~= yind1)/numel(tind1);
correctRate1 = 1-percentErrors1;

fprintf('CNN Testing Data from Test - Hue Histogram Features Performance: %d CorrectRate: %f ErrorRate: %f \n',...
    performance1,...
    correctRate1, percentErrors1);

%% Categorical

[cnn_pred_classes_names, cnn_pred_classes_categ] = classid_to_name(trainClasses);
[test_known_classes_names, test_known_classes_categ] = classid_to_name(testClasses);

% flip dimensions
cnn_pred_classes_names = cnn_pred_classes_names';
cnn_pred_classes_categ = cnn_pred_classes_categ';
test_known_classes_names = test_known_classes_names';
test_known_classes_categ = test_known_classes_categ';

categories = {'speed', 'cancel', ...
     'priority', 'prohibitory','warning', ...
     'mandatory'};

% trainClasses, testClasses
% Set train labels for Hue Histogram Categories
train_categ_labels = zeros(length(cnn_pred_classes_categ),6);
for i=1:length(cnn_pred_classes_categ)
    if (cellfun(@isequal, cnn_pred_classes_categ(i), {'speed'}))
        train_categ_labels(i,1) = 1;
    elseif (cellfun(@isequal, cnn_pred_classes_categ(i), {'cancel'}))
        train_categ_labels(i,2) = 1;
    elseif (cellfun(@isequal, cnn_pred_classes_categ(i), {'priority'}))
        train_categ_labels(i,3) = 1;
    elseif (cellfun(@isequal, cnn_pred_classes_categ(i), {'prohibitory'}))
        train_categ_labels(i,4) = 1;
    elseif (cellfun(@isequal, cnn_pred_classes_categ(i), {'warning'}))
        train_categ_labels(i,5) = 1;
    elseif (cellfun(@isequal, cnn_pred_classes_categ(i), {'mandatory'}))
        train_categ_labels(i,6) = 1;
    end
end

% Set test labels for Hue Histogram Categories
test_categ_labels = zeros(length(test_known_classes_categ),6);
for i=1:length(test_known_classes_categ)
   if (cellfun(@isequal, test_known_classes_categ(i), {'speed'}))
        test_categ_labels(i,1) = 1;
    elseif (cellfun(@isequal, test_known_classes_categ(i), {'cancel'}))
        test_categ_labels(i,2) = 1;
    elseif (cellfun(@isequal, test_known_classes_categ(i), {'priority'}))
        test_categ_labels(i,3) = 1;
    elseif (cellfun(@isequal, test_known_classes_categ(i), {'prohibitory'}))
        test_categ_labels(i,4) = 1;
    elseif (cellfun(@isequal, test_known_classes_categ(i), {'warning'}))
        test_categ_labels(i,5) = 1;
    elseif (cellfun(@isequal, test_known_classes_categ(i), {'mandatory'}))
        test_categ_labels(i,6) = 1;
    end 
end

%% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created 05-May-2020 16:20:41
%
% This script assumes these variables are defined:
%
%   train_hue_features - input data.
%   train_categ_labels - target data.

x11 = train_hue_features';
t11 = train_categ_labels';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainscg';  % Scaled conjugate gradient backpropagation.

% Create a Pattern Recognition Network
hiddenLayerSize = 40;
net11 = patternnet(hiddenLayerSize, trainFcn);

% Setup Division of Data for Training, Validation, Testing
net11.divideParam.trainRatio = 70/100;
net11.divideParam.valRatio = 15/100;
net11.divideParam.testRatio = 15/100;

% Train the Network
[net11,tr] = train(net11,x11,t11);

% Test the Network
y11 = net11(x11);
e11 = gsubtract(t11,y11);
performance11 = perform(net11,t11,y11)
tind11 = vec2ind(t11);
yind11 = vec2ind(y11);
percentErrors11 = sum(tind11 ~= yind11)/numel(tind11);
correctRate11 = 1-percentErrors11;
% View the Network
view(net11)

fprintf('CNN Testing Data from Training - Hue Histogram Categorical Performance: %d CorrectRate: %f ErrorRate: %f \n',...
    performance11,...
    correctRate11, percentErrors11);
% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotconfusion(t,y)
%figure, plotroc(t,y)

%% Test against testing data
xx11 = test_hue_features';
tt11 = test_categ_labels';
% Test the Network
yy11 = net11(xx11);
ee11 = gsubtract(tt11,yy11);
performance111 = perform(net11,tt11,yy11);
tind11 = vec2ind(tt11);
yind11 = vec2ind(yy11);
percentErrors111 = sum(tind11 ~= yind11)/numel(tind11);
correctRate111 = 1-percentErrors111;

fprintf('CNN Testing Data from Test - Hue Histogram Features Performance: %d CorrectRate: %f ErrorRate: %f \n',...
    performance111,...
    correctRate111, percentErrors111);

pred_classes_categ = {''};

for i = 1:length(test_known_classes_categ)
    [val,idx] = max(yy11(:,i));
    pred_classes_categ(i) = categories(idx);
end

pred_classes_categ = pred_classes_categ';

figure;
cm = confusionchart(test_known_classes_categ, pred_classes_categ, 'RowSummary','row-normalized','ColumnSummary','column-normalized');
% This will sort based on the true positive rate
cm.Normalization = 'row-normalized'; 
sortClasses(cm,'descending-diagonal')
cm.Normalization = 'absolute';
title('CNN Categorical: Histogram of Hues');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Part 3 with Improved Contrast PCA basis
%  Performance is quite a bit better with the PCA basis
%% Setup

%basePath = 'C:/Users/casxi/Google Drive/Documents/JHU/Machine Learning for Signal Processing/Final Project/gtsrb-german-traffic-sign/'; 
basePath = fullfile(fileparts(fullfile(mfilename('fullpath'))),'..','gtsrb-german-traffic-sign/');

trainCsv = 'Train.csv';
testCsv = 'Test.csv';
metaCsv = 'Meta.csv';

%% Data Conditioning

% [OPTIONAL] Only use the highest quality training and test images
[trainPaths, trainWidths, trainHeights, trainRoiX1, trainRoiY1, trainRoiX2, trainRoiY2, trainClasses]  = reduce_dataset(basePath, trainCsv, .75, .75);
[testPaths, testWidths, testHeights, testRoiX1, testRoiY1, testRoiX2, testRoiY2, testClasses]  = reduce_dataset(basePath, testCsv, .75, .75);

% Get the resized images in matrix form. Each row is a grey intensity image
% This captures the ROI before resizing.
% This essentially captures creates our dataset where the pixel intensities
% are the features we are using for each sign.
trainImages = get_images(basePath, trainPaths, trainRoiX1, trainRoiY1, trainRoiX2, trainRoiY2, 50, 50, 'roi');
testImages = get_images(basePath, testPaths, testRoiX1, testRoiY1, testRoiX2, testRoiY2, 50, 50, 'roi');

trainImages = boost_gray_contrast(trainImages);
testImages = boost_gray_contrast(testImages);

%% Feature Extraction

% Extract PCA features

[eigsigns, eigvals] = pca_basis(trainImages, 40);

train_pca_features = trainImages*eigsigns;
test_pca_features = testImages*eigsigns;

% Set train labels for CNN
train_cnn_labels_2 = zeros(length(trainClasses),max(trainClasses)+1);
for i=1:length(trainClasses)
   train_cnn_labels_2(i,trainClasses(i)+1) = 1; 
end

% Set test labels for CNN
test_cnn_labels2 = zeros(length(testClasses),max(testClasses)+1);
for i=1:length(testClasses)
   test_cnn_labels2(i,testClasses(i)+1) = 1; 
end

%% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created 03-May-2020 02:20:36
%
% This script assumes these variables are defined:
%
%   trainImages - input data.
%   train_cnn_labels_2 - target data.

x3 = trainImages';
t3 = train_cnn_labels_2';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainscg';  % Scaled conjugate gradient backpropagation.

% Create a Pattern Recognition Network
hiddenLayerSize = 40;
netc = patternnet(hiddenLayerSize, trainFcn);

% Setup Division of Data for Training, Validation, Testing
netc.divideParam.trainRatio = 70/100;
netc.divideParam.valRatio = 15/100;
netc.divideParam.testRatio = 15/100;

% Train the Network
[netc,tr] = train(netc,x3,t3);

% Test the Network
y3 = netc(x3);
e3 = gsubtract(t3,y3);
performance3 = perform(netc,t3,y3)
tind3 = vec2ind(t3);
yind3 = vec2ind(y3);
percentErrors3 = sum(tind3 ~= yind3)/numel(tind3);
correctRate3 = 1-percentErrors3;

% View the Network
view(netc)

fprintf('CNN Testing Data from Training - PCA Improved Gray Contrast - PCA Basis: %d Performance: %d CorrectRate: %f ErrorRate: %f \n',...
    40,...    
    performance3,...
    correctRate3, percentErrors3);


%% Test against testing data
x4 = testImages';
t4 = test_cnn_labels2';
% Test the Network
y4 = netc(x4);
e4 = gsubtract(t4,y4);
performance4 = perform(netc,t4,y4);
tind4 = vec2ind(t4);
yind4 = vec2ind(y4);
percentErrors4 = sum(tind4 ~= yind4)/numel(tind4);
correctRate4 = 1-percentErrors4;

fprintf('CNN Testing Data from Test - PCA Basis: %d Performance: %d CorrectRate: %f ErrorRate: %f \n',...
    40,...
    performance4,...
    correctRate4, percentErrors4);

figure, plotconfusion(t4,y4)

%% Categorical

[cnn_pred_classes_names, cnn_pred_classes_categ] = classid_to_name(trainClasses);
[test_known_classes_names, test_known_classes_categ] = classid_to_name(testClasses);

% flip dimensions
cnn_pred_classes_names = cnn_pred_classes_names';
cnn_pred_classes_categ = cnn_pred_classes_categ';
test_known_classes_names = test_known_classes_names';
test_known_classes_categ = test_known_classes_categ';

categories = {'speed', 'cancel', ...
     'priority', 'prohibitory','warning', ...
     'mandatory'};

% trainClasses, testClasses
% Set train labels for Hue Histogram Categories
train_categ_labels = zeros(length(cnn_pred_classes_categ),6);
for i=1:length(cnn_pred_classes_categ)
    if (cellfun(@isequal, cnn_pred_classes_categ(i), {'speed'}))
        train_categ_labels(i,1) = 1;
    elseif (cellfun(@isequal, cnn_pred_classes_categ(i), {'cancel'}))
        train_categ_labels(i,2) = 1;
    elseif (cellfun(@isequal, cnn_pred_classes_categ(i), {'priority'}))
        train_categ_labels(i,3) = 1;
    elseif (cellfun(@isequal, cnn_pred_classes_categ(i), {'prohibitory'}))
        train_categ_labels(i,4) = 1;
    elseif (cellfun(@isequal, cnn_pred_classes_categ(i), {'warning'}))
        train_categ_labels(i,5) = 1;
    elseif (cellfun(@isequal, cnn_pred_classes_categ(i), {'mandatory'}))
        train_categ_labels(i,6) = 1;
    end
end

% Set test labels for Hue Histogram Categories
test_categ_labels = zeros(length(test_known_classes_categ),6);
for i=1:length(test_known_classes_categ)
   if (cellfun(@isequal, test_known_classes_categ(i), {'speed'}))
        test_categ_labels(i,1) = 1;
    elseif (cellfun(@isequal, test_known_classes_categ(i), {'cancel'}))
        test_categ_labels(i,2) = 1;
    elseif (cellfun(@isequal, test_known_classes_categ(i), {'priority'}))
        test_categ_labels(i,3) = 1;
    elseif (cellfun(@isequal, test_known_classes_categ(i), {'prohibitory'}))
        test_categ_labels(i,4) = 1;
    elseif (cellfun(@isequal, test_known_classes_categ(i), {'warning'}))
        test_categ_labels(i,5) = 1;
    elseif (cellfun(@isequal, test_known_classes_categ(i), {'mandatory'}))
        test_categ_labels(i,6) = 1;
    end 
end

%% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created 05-May-2020 15:57:52
%
% This script assumes these variables are defined:
%
%   trainImages - input data.
%   train_categ_labels - target data.

x5 = trainImages';
t5 = train_categ_labels';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainscg';  % Scaled conjugate gradient backpropagation.

% Create a Pattern Recognition Network
hiddenLayerSize = 40;
net5 = patternnet(hiddenLayerSize, trainFcn);

% Setup Division of Data for Training, Validation, Testing
net5.divideParam.trainRatio = 70/100;
net5.divideParam.valRatio = 15/100;
net5.divideParam.testRatio = 15/100;

% Train the Network
[net5,tr] = train(net5,x5,t5);

% Test the Network
y5 = net5(x5);
e5 = gsubtract(t5,y5);
performance5 = perform(net5,t5,y5)
tind5 = vec2ind(t5);
yind5 = vec2ind(y5);
percentErrors5 = sum(tind5 ~= yind5)/numel(tind5);
correctRate5 = 1-percentErrors5;

% View the Network
view(net5)

fprintf('CNN Testing Data from Training - PCA Categorical - PCA Basis: %d Performance: %d CorrectRate: %f ErrorRate: %f \n',...
    40,...    
    performance5,...
    correctRate5, percentErrors5);

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotconfusion(t,y)
%figure, plotroc(t,y)

%% Test against testing data
x6 = testImages';
t6 = test_categ_labels';
% Test the Network
y6 = net5(x6);
e6 = gsubtract(t6,y6);
performance6 = perform(net5,t6,y6);
tind6 = vec2ind(t6);
yind6 = vec2ind(y6);
percentErrors6 = sum(tind6 ~= yind6)/numel(tind6);
correctRate6 = 1-percentErrors6;

fprintf('CNN Testing Data from Test - PCA Categorical - PCA Basis: %d Performance: %d CorrectRate: %f ErrorRate: %f \n',...
    40,...
    performance6,...
    correctRate6, percentErrors6);

%figure, plotconfusion(t6,y6)

pred_classes_categ = {''};

for i = 1:length(test_known_classes_categ)
    [val,idx] = max(y6(:,i));
    pred_classes_categ(i) = categories(idx);
end

pred_classes_categ = pred_classes_categ';

figure;
cm = confusionchart(test_known_classes_categ, pred_classes_categ, 'RowSummary','row-normalized','ColumnSummary','column-normalized');
% This will sort based on the true positive rate
cm.Normalization = 'row-normalized'; 
sortClasses(cm,'descending-diagonal')
cm.Normalization = 'absolute';
title(['CNN Categorical: Histogram Equalization - PCA Basis: ',num2str(40)]);
